# Generated by Django 2.2.7 on 2019-11-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.CharField(max_length=200)),
                ('encoding_text', models.CharField(max_length=200)),
            ],
        ),
    ]
